---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    app.quarkus.io/commit-id: c2c601406e56368cc2902ce9901f5fb8acd8e90d
    app.quarkus.io/build-timestamp: 2022-02-21 - 16:33:24 +0000
  labels:
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/name: harry-potter-quarkus
  name: harry-potter-quarkus
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/commit-id: c2c601406e56368cc2902ce9901f5fb8acd8e90d
    app.quarkus.io/build-timestamp: 2022-02-21 - 16:33:24 +0000
  labels:
    app.kubernetes.io/name: harry-potter-quarkus
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: harry-potter-quarkus
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: harry-potter-quarkus
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: view-secrets
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: harry-potter-quarkus-view
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: view
subjects:
  - kind: ServiceAccount
    name: harry-potter-quarkus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: harry-potter-quarkus-view-secrets
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: view-secrets
subjects:
  - kind: ServiceAccount
    name: harry-potter-quarkus
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/commit-id: c2c601406e56368cc2902ce9901f5fb8acd8e90d
    app.quarkus.io/build-timestamp: 2022-02-21 - 16:33:24 +0000
  labels:
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/name: harry-potter-quarkus
  name: harry-potter-quarkus
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
      app.kubernetes.io/name: harry-potter-quarkus
  template:
    metadata:
      annotations:
        app.quarkus.io/commit-id: c2c601406e56368cc2902ce9901f5fb8acd8e90d
        app.quarkus.io/build-timestamp: 2022-02-21 - 16:33:24 +0000
      labels:
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
        app.kubernetes.io/name: harry-potter-quarkus
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: fabio/harry-potter-quarkus:1.0.0-SNAPSHOT
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          name: harry-potter-quarkus
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
      serviceAccountName: harry-potter-quarkus
